### ISSUE TITLE
Things to add on slide for "Other Resources"

### ISSUE THREAD

**Issue by simonmcs** [HandsOnOpenCL/Lecture-Slides#11]
Ideas for now:
- CLU: https://github.com/Computing-Language-Utility/CLU
- clMath: https://github.com/clMathLibraries/clBLAS and https://github.com/clMathLibraries/clFFT

Anything else?

**Comment by tomdeakin** [comment]
Have we mentioned a link to the spec itself yet or should we put that in here anyway?

**Comment by simonmcs** [comment]
OK I've updated the "other resource" section, adding all the suggestions.
