### ISSUE TITLE
Might need to use a different courier font

### ISSUE THREAD

**Issue by simonmcs** [HandsOnOpenCL/Lecture-Slides#13]
Feedback from Neil Trevett:

"On my machine Courier Font is very block – Courier New is much better."

We should check what this looks like on a couple of different machines and see what an appropriate fix is so that the Courier font looks good on most machines.

**Comment by tomdeakin** [comment]
Can switch to Courier New if needed. How does this font look for you?
It shouldn't take too long.

**Comment by simonmcs** [comment]
Switched all the slides to courier new.
