### ISSUE TITLE
Add a slide on using OpenCL on Intel GPUs

### ISSUE THREAD

**Issue by simonmcs** [HandsOnOpenCL/Lecture-Slides#15]
We've had feedback from Intel that it would be nice to include a slide on how to use OpenCL on their GPUs. This will be great to include, but the information is not public yet, at least for Linux, so we'll do this once we've got the info from Intel.

We actually _could_ do this for Mac OS X 10.9 "Mavericks" when that's released, as Apple have already announced that this will include OpenCL 1.2 support for integrated Intel graphics (and Nvidia too).

**Comment by tomdeakin** [comment]
done
