### ISSUE TITLE
Do we need to add something about the ICD?

### ISSUE THREAD

**Issue by simonmcs** [HandsOnOpenCL/Lecture-Slides#18]
Do we need to say anything about the ICD in the getting started section?

**Comment by tomdeakin** [comment]
This would be really helpful to include some info on what it is and what it gives you.

Would you like me to add this?

**Comment by simonmcs** [comment]
Yes please Tom, that'd be great!

Simon

On 6 Oct 2013, at 20:29, Tom Deakin notifications@github.com wrote:

> This would be really helpful to include some info on what it is and what it gives you.
> 
> Would you like me to add this?
> 
> —
> Reply to this email directly or view it on GitHub.

## 

Head of Microelectronics Group and University of Bristol Business Fellow
High Performance Computing and Architectures, Department of Computer Science
University of Bristol, Merchant Venturers Building, Woodland Road, Clifton, Bristol, BS8 1UB, UK
Phone: +44 (0)117 331 5324, Twitter: simonmcs, Web: http://www.cs.bris.ac.uk/~simonm/
Microelectronics Group webpage: http://www.cs.bris.ac.uk/Research/Micro/

**Comment by tomdeakin** [comment]
Did we upload and release this version?

**Comment by simonmcs** [comment]
Not yet - I'm in the middle of making a few more changes before releasing a new version! 

In particular we've had feedback from some of the vendors which I'm folding in, and I want to change the optimised matrix multiply example to the one we used at SC13. This new one was derived from scratch but ends up with similar performance to the Nvidia-derived one.

**Comment by tomdeakin** [comment]
done
