### ISSUE TITLE
Add material on buffer management

### ISSUE THREAD

**Issue by simonmcs** [HandsOnOpenCL/Lecture-Slides#20]
Feedback from a user in a large commercial OpenCL-supporting company:

"My 2 cents: i) add a chapter on buffer managements (map and read/write) as part of the opencl intro. This is to include a discussion about the usage and semantic differences between map/unmap and read/write and migrate and ii) discuss the ability to overlap communication with computations via out of order queues or multiple queues in the optimization chapter. This is one of the more important optimizations for OpenCL on discrete accelerators."

**Comment by tomdeakin** [comment]
done
