### ISSUE TITLE
where are the actual slides

### ISSUE THREAD

**Issue by MySchizoBuddy** [HandsOnOpenCL/Lecture-Slides#21]
this repo is for issue tracking the slides. but where are the slides themselves? I cannot find them anywhere. The website HandsOnOpenCl doesn't explain where to get the slides?

**Comment by tomdeakin** [comment]
The slides are in the [releases tab](https://github.com/HandsOnOpenCL/Lecture-Slides/releases) in PowerPoint format. Git and the PowerPoint format don't work together very well and so we have just uploaded incremental versions of the slides to releases.

**Comment by tomdeakin** [comment]
I've updated the http://handsonopencl.github.io/ page with a link to the slides now.
